# Create a PVC to store files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-wordcount-pvc
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi   # Lets ask for 10GB. Change it if we needs it to be smaller
  accessModes:
    - ReadWriteMany
  storageClassName: slow   #Update if the k8s has no default storage class.

