apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-master-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /mnt/nfs
    server: 10.215.241.171
    readOnly: false
